import fs from 'node:fs';
import path from 'node:path';

const [protoPath, jsPath, declarationPath] = process.argv.slice(2);
if (!protoPath || !jsPath || !declarationPath) {
  throw new Error('Usage: node postprocess_steam_protobuf.mjs <proto> <js> <d.ts>');
}

const readUtf8 = (filePath) => fs.readFileSync(filePath, 'utf8');
const writeUtf8 = (filePath, content) => fs.writeFileSync(filePath, content, 'utf8');

/** Converts protobuf snake_case field names to the camelCase names emitted by protobufjs. */
function toCamelCase(name) {
  // protobufjs camel-cases alphabetic segments but preserves names such as secret_1.
  return name.replace(/_([a-z])/g, (_match, letter) => letter.toUpperCase());
}

/** Maps a protobuf field type to the corresponding protobufjs declaration type. */
function toTypeScriptType(protoType, messageNames, enumNames) {
  const numberTypes = new Set([
    'double', 'float', 'int32', 'uint32', 'sint32', 'fixed32', 'sfixed32'
  ]);
  const longTypes = new Set([
    'int64', 'uint64', 'sint64', 'fixed64', 'sfixed64'
  ]);
  if (numberTypes.has(protoType)) return 'number';
  if (longTypes.has(protoType)) return 'Long';
  if (protoType === 'bool') return 'boolean';
  if (protoType === 'string') return 'string';
  if (protoType === 'bytes') return 'Uint8Array';
  if (enumNames.has(protoType)) return protoType;
  if (messageNames.has(protoType)) return `(I${protoType}|null)`;
  throw new Error(`Unsupported protobuf type: ${protoType}`);
}

/** Builds missing protobufjs I* property interfaces directly from the canonical .proto file. */
function parseProtoMessages(protoSource) {
  const withoutComments = protoSource
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\/\/.*$/gm, '');
  const messages = [...withoutComments.matchAll(/\bmessage\s+(\w+)\s*\{([\s\S]*?)\}/g)];
  const messageNames = new Set(messages.map((match) => match[1]));
  const enumNames = new Set(
    [...withoutComments.matchAll(/\benum\s+(\w+)\s*\{/g)].map((match) => match[1])
  );

  return { messages, messageNames, enumNames };
}

function buildInterfaceBlock(protoSource, missingNames) {
  const { messages, messageNames, enumNames } = parseProtoMessages(protoSource);
  const declarations = messages
    .filter((messageMatch) => missingNames.has(messageMatch[1]))
    .map((messageMatch) => {
    const [, messageName, body] = messageMatch;
    const fields = [...body.matchAll(
      /\b(optional|required|repeated)\s+([.\w]+)\s+(\w+)\s*=\s*\d+(?:\s*\[[^\]]*\])?\s*;/g
    )];
    const properties = fields.map((fieldMatch) => {
      const [, rule, rawType, fieldName] = fieldMatch;
      const protoType = rawType.replace(/^\./, '');
      let fieldType = toTypeScriptType(protoType, messageNames, enumNames);
      if (rule === 'repeated') {
        fieldType = fieldType.startsWith('(I')
          ? `${fieldType.slice(1, -6)}[]`
          : `${fieldType}[]`;
      }
      return `    ${toCamelCase(fieldName)}?: ${fieldType};`;
    });
    const bodyText = properties.length > 0 ? `\n${properties.join('\n')}\n` : '\n';
    return `/** Properties of a ${messageName}. */\nexport interface I${messageName} {${bodyText}}`;
    });

  return [
    '// <auto-generated-protobuf-interfaces>',
    '// protobufjs-cli 1.1.3 omits message interfaces when top-level enums are present.',
    '// These compatibility declarations are regenerated from steam_auth.proto.',
    ...declarations,
    '// </auto-generated-protobuf-interfaces>'
  ].join('\n\n');
}

/** Applies the small runtime import adaptation required by the HarmonyOS protobuf package. */
function adaptRuntimeModule(source) {
  const runtimeImport = [
    "import { index } from '@ohos/protobufjs';",
    "import Long from 'long';",
    'const $protobuf = index;',
    '$protobuf.util.Long = Long;',
    '$protobuf.configure();'
  ].join('\n');
  return source.replace(
    /import \* as \$protobuf from ["']protobufjs\/minimal["'];/,
    runtimeImport
  );
}

/** Adds generated compatibility interfaces when pbts omitted them and applies ArkTS-safe imports. */
function adaptDeclarationModule(source, protoSource) {
  let result = source.replace(
    /import \* as \$protobuf from ["']protobufjs["'];/,
    "import * as $protobuf from '@ohos/protobufjs';"
  );
  result = result.replace(/\(number\|Long\)/g, 'Long');

  const markerPattern = /\/\/ <auto-generated-protobuf-interfaces>[\s\S]*?\/\/ <\/auto-generated-protobuf-interfaces>\s*/;
  result = result.replace(markerPattern, '');
  const { messageNames } = parseProtoMessages(protoSource);
  const missingNames = new Set(
    [...messageNames].filter((messageName) => {
      const definition = new RegExp(`\\bexport interface I${messageName}\\b`);
      return !definition.test(result);
    })
  );
  if (missingNames.size === 0) {
    return result;
  }
  const interfaces = buildInterfaceBlock(protoSource, missingNames);
  const firstClass = result.indexOf('/** Represents a ');
  if (firstClass < 0) {
    throw new Error('Cannot locate the first generated protobuf class declaration.');
  }
  return `${result.slice(0, firstClass)}${interfaces}\n\n${result.slice(firstClass)}`;
}

const protoSource = readUtf8(protoPath);
writeUtf8(jsPath, adaptRuntimeModule(readUtf8(jsPath)));
writeUtf8(declarationPath, adaptDeclarationModule(readUtf8(declarationPath), protoSource));

console.log(`Post-processed ${path.basename(jsPath)} and ${path.basename(declarationPath)}.`);
